[tool.isort]
profile = "black"
line_length = "120"
known_pytorch = ["torch", "torchaudio", "torchtext", "torchvision"]
known_openmmlab = ["mmcv", "mmcls", "mmdet"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "PYTORCH", "OPENMMLAB", "FIRSTPARTY", "LOCALFOLDER"]

[tool.black]
line-length = 120
include = "liedet/"

[tool.mypy]
python_version = "3.9"
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
local_partial_types = true
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true