scanner:
  diff_only: False  # The entire file touched by the PR will be scanned for errors
  linter: flake8

flake8:
  max-line-length: 80  # Default is 79 in PEP 8
  ignore: [E501, E203]

no_blank_comment: False  # Every PR will have its own pep8speaks stats
