name: env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - wget

  - cudatoolkit-dev=11.3

  - pip:
      - --find-links https://download.pytorch.org/whl/cu113/torch_stable.html
      - --find-links https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html
      - -r requirements-cu113.txt
      - -r requirements.txt
      - -r dev-requirements.txt
